server:
  port: 9999
  
zuul:
  ignored-services: "*"
  routes:
    BookingService:
      path: /booking/**
      serviceId: Cargobooking
      stripPrefix: true
    CargoTrackerService:
      path: /tracker/**
      serviceId: Cargotracker
      stripPrefix: true
    PathfinderService: 
      path: /pathfinder/**
      serviceId: Pathfinder
      stripPrefix: true
    CargoUserService: 
      path: /user/**
      serviceId: Cargouser
      stripPrefix: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 
