"use strict";
// DO NOT EDIT THIS FILE, EDIT THE GRUNT TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
var authUrl;
authUrl = '';
var accountUrl;
accountUrl = '';

angular.module('sampleAdminWebApp')

.constant('ENV', 'dev')
.constant('VERSION', '0.0.1-SNAPSHOT')

.constant('OAUTH_CLIENT_ID', 'auth')
.constant('OAUTH_CLIENT_SECRET', 'authSecret')

.constant('AUTHORIZATION_SERVER_URL', authUrl)
.constant('AUTHORIZATION_SERVER_AUTHORIZE_URL', authUrl + 'oauth/authorize')
.constant('AUTHORIZATION_SERVER_OAUTH_TOKEN_URL', authUrl + 'oauth/token')
.constant('AUTHORIZATION_SERVER_CHECK_TOKEN_URL', authUrl + 'oauth/check_token')


.constant('ACCOUNT_SERVER_URL', accountUrl)
.constant('ACCOUNT_SERVICE_URL', accountUrl + 'api/account')
.constant('ACTIVATE_SERVICE_URL', accountUrl + 'api/activate')
.constant('LOGOUT_SERVICE_URL', accountUrl + 'api/logout')

.constant('REGISTER_SERVICE_URL', accountUrl + 'api/register')
.constant('CHANGE_PASSWORD_SERVICE_URL', accountUrl + 'api/account/change_password')

.constant('CLIENTS_SERVICE_URL', accountUrl + 'api/admin/clients')
.constant('AUTHORITIES_SERVICE_URL', accountUrl + 'api/admin/authorities')
.constant('USERS_SERVICE_URL', accountUrl + 'api/admin/users')

.constant('TA_API_HOST','')
.constant('MOC_API_HOST','')
.constant('LCA_API_HOST','')
.constant('SAMPLE_API_HOST','')
;
